version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    executor:
      name: node/default
    working_directory: ~/portfolio
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    docker:
      - image: "cimg/python:3.6"
    working_directory: ~/portfolio
    steps:
      - checkout
      - attach_workspace:
          at: ~/portfolio
      - aws-s3/sync:
          from: dist
          to: "s3://$S3_BUCKET_NAME"
          arguments: --delete
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
